### ISSUE TITLE
npm install refers to digium private stash

### ISSUE THREAD

**Issue by steely-glint** [respoke/respoke#1]
I ran 
 npm install -g grunt
 npm install
and got errors like this :

478 error Error: Command failed: Cloning into bare repository '/Users/tim/.npm/_git-remotes/ssh-git-stash-digium-com-7999-stratos-grunt-stratos-git-118a5c20'...
478 error ssh: Could not resolve hostname stash.digium.com: nodename nor servname provided, or not known
478 error fatal: Could not read from remote repository.
478 error
478 error Please make sure you have the correct access rights
478 error and the repository exists.
478 error
478 error     at ChildProcess.exithandler (child_process.js:637:15)
478 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
478 error     at maybeClose (child_process.js:743:16)
478 error     at Socket.<anonymous> (child_process.js:956:11)
478 error     at Socket.EventEmitter.emit (events.js:95:17)
478 error     at Pipe.close (net.js:465:12)

**Comment by ruffrey** [comment]
`grunt-stratos` is no longer in package.json. Closing for now but feel free to reopen.
